fields:
  general:
    type: section
  deep:
    type: toggle
    instructions: If set to false, you can manually add it to a request using <code>?deep=true</code>
    width: 50
  nested:
    type: toggle
    instructions: If set to false, you can manually add it to a request using <code>?nested=true</code>
    width: 50
  index_collections:
    type: collections
    display: Auto-Index Collections
    instructions: This is essential for use with Search, otherwise the search index will be out of sync.
  authentication:
    type: section
  enable_api_key:
    type: toggle
    display: Enable API Key
  api_key:
    type: fetch
    display: API Key
  ip_whitelist:
    type: list
    display: IP Whitelist
    instructions: Leave blank to allow requests from any IP address
  domain_whitelist:
    type: list
    display: Domain Whitelist
    instructions: Leave blank to allow requests from any Domain
